import { create } from 'zustand';
import { 
  TopologyNode, 
  TopologyEdge, 
  NodeType, 
  NodeStatus, 
  Priority, 
  AgentRole, 
  ExecutionType,
  ModelEngine,
  EdgeType, 
  ThemeMode, 
  ViewMode,
  TopologyStats,
  SubgraphStackFrame,
  CoherenceReport,
  AgentTelemetry,
  LevelOfDetail,
  ArtifactPayload,
  AgentWorker,
  AgentActivityEvent,
  MultiAgentCollaborationMode,
  SharedContextEntry,
  SharedContextRepository
} from '../types/topology';
import { SAMPLE_TOPOLOGIES, DEFAULT_AGENT_SQUAD } from '../data/sampleTopologies';
import { CANONICAL_ARCHETYPES, CanonicalArchetype } from '../data/topologyRegistry';
import { calculateDagreLayout, detectCycles, getTopologicalBatches } from '../utils/graphAlgorithms';
import { importFromObsidianCanvas } from '../utils/obsidianCanvas';
import { validateGraphCoherence } from '../utils/graphValidation';

export function createSyntheticArtifactPayload(name: string, engine: string = 'gemini-2.5-pro', label = 'Task'): ArtifactPayload {
  const isTs = name.endsWith('.ts') || name.endsWith('.tsx');
  const isJson = name.endsWith('.json');
  const isMd = name.endsWith('.md');
  const mimeType: ArtifactPayload['mimeType'] = isTs ? 'text/typescript' : isJson ? 'application/json' : isMd ? 'text/markdown' : 'text/plain';

  let content = '';
  if (isJson) {
    content = JSON.stringify({
      version: "1.0.0",
      engine: engine,
      task: label,
      status: "validated",
      timestamp: new Date().toISOString(),
      metadata: {
        invariantsChecked: true,
        hash: Math.random().toString(36).substring(2, 10),
      }
    }, null, 2);
  } else if (isTs) {
    content = `// Auto-generated by ${engine} for [${label}]
// Timestamp: ${new Date().toISOString()}

export interface ContractConfig {
  id: string;
  name: string;
  active: boolean;
  timestamp: number;
}

export async function executePlanTask(params: Record<string, unknown>): Promise<{ success: boolean; data: ContractConfig }> {
  return {
    success: true,
    data: {
      id: "contract_${Math.random().toString(36).substring(2, 6)}",
      name: "${name}",
      active: true,
      timestamp: Date.now(),
    }
  };
}
`;
  } else if (isMd) {
    content = `# Deliverable: ${name}
> Generated autonomously by **${engine}**
> Target: **${label}**

## Executive Summary
This document confirms the verification and synthesis of ${name}. All causal dependencies and boundary invariants have been fulfilled.

## Invariant Checklist
- [x] Schema contract verified
- [x] Cyclic paths eliminated
- [x] Ready for downstream ingestion
`;
  } else {
    content = `Artifact Payload: ${name}\nGenerated by: ${engine}\nTarget: ${label}\nTimestamp: ${new Date().toISOString()}`;
  }

  return {
    name,
    content,
    mimeType,
    sizeBytes: content.length,
    updatedAt: Date.now(),
  };
}

interface HistoryState {
  nodes: TopologyNode[];
  edges: TopologyEdge[];
}

interface TopologyStore {
  // Data
  nodes: TopologyNode[];
  edges: TopologyEdge[];
  selectedNodeId: string | null;
  selectedNodeIds: string[];
  hoveredNodeId: string | null;

  // Subgraph Hierarchy Stack
  subgraphStack: SubgraphStackFrame[];
  enterSubgraph: (nodeId: string) => void;
  exitSubgraph: () => void;
  navigateToBreadcrumb: (index: number) => void;

  // View & Theme & LOD & Orientation
  theme: ThemeMode;
  viewMode: ViewMode;
  lod: LevelOfDetail;
  layoutDirection: 'LR' | 'TB';
  setLayoutDirection: (dir: 'LR' | 'TB') => void;
  toggleLayoutDirection: () => void;

  // Filters & Search
  searchQuery: string;
  filterExecutionType: ExecutionType | 'all';
  filterRole: AgentRole | 'all';
  filterStatus: NodeStatus | 'all';
  filterType: NodeType | 'all';

  // Simulation State
  isSimulating: boolean;
  simulationStep: number;
  simulationBatches: string[][];

  // History
  history: HistoryState[];
  future: HistoryState[];

  // CRUD Actions
  addNode: (partial?: Partial<TopologyNode>, options?: { autoConnect?: boolean; targetId?: string }) => TopologyNode;
  updateNode: (id: string, updates: Partial<TopologyNode>) => void;
  deleteNode: (id: string) => void;
  connectNodes: (sourceId: string, targetId: string, type?: EdgeType, label?: string, condition?: 'true' | 'false' | 'always') => { success: boolean; error?: string };
  removeEdge: (edgeId: string) => void;
  selectNode: (id: string | null) => void;
  setSelectedNodeIds: (ids: string[]) => void;
  toggleNodeSelection: (id: string, multi?: boolean) => void;
  clearNodeSelection: () => void;
  setHoveredNode: (id: string | null) => void;
  setLod: (lod: LevelOfDetail) => void;

  // Multi-Node Batch Operations
  bundleSelectedIntoSubgraph: (label?: string) => void;
  alignSelectedNodes: (direction: 'horizontal' | 'vertical') => void;
  batchSetStatus: (status: NodeStatus) => void;
  batchDeleteNodes: () => void;

  // HITL & Decision Gate Operations
  approveNode: (nodeId: string, notes?: string) => void;
  rejectNode: (nodeId: string, notes?: string) => void;
  toggleApprovalRequired: (nodeId: string) => void;
  evaluateDecisionBranch: (nodeId: string, conditionResult: boolean) => void;

  // Rapid Workflow Shortcuts & Smart Heuristics
  findSmartConnectTarget: (pos: { x: number; y: number }, type?: NodeType) => TopologyNode | null;
  branchChildNode: (parentId: string) => TopologyNode;
  createSiblingNode: (referenceId: string) => TopologyNode;

  // Autonomous Multi-Agent Runner
  runAutonomousAgent: (nodeId: string) => void;

  // Coherence Diagnostics & Auto-Fixes
  getCoherenceReport: () => CoherenceReport;
  applyAutoFix: (issueId: string) => void;

  // Auto Layout
  applyDagreLayout: (direction?: 'LR' | 'TB') => void;

  // Simulation Controls
  startSimulation: () => void;
  stepSimulation: () => void;
  pauseSimulation: () => void;
  resetSimulation: () => void;

  // Multi-Agent Swarm State & Observability
  globalSquad: AgentWorker[];
  activityStream: AgentActivityEvent[];
  isCockpitOpen: boolean;
  activeFilterAgentId: string | null;

  // Multi-Agent Swarm Actions
  setCockpitOpen: (isOpen: boolean) => void;
  setActiveFilterAgentId: (agentId: string | null) => void;
  addActivityEvent: (event: Omit<AgentActivityEvent, 'id' | 'timestamp'>) => void;
  clearActivityStream: () => void;
  loadMultiAgentDemo: () => void;
  assignAgentToNode: (nodeId: string, agent: AgentWorker) => void;
  removeAgentFromNode: (nodeId: string, agentId: string) => void;
  setNodeCollaborationMode: (nodeId: string, mode: MultiAgentCollaborationMode) => void;

  // View & Theme Controls
  setTheme: (theme: ThemeMode) => void;
  toggleTheme: () => void;
  setViewMode: (mode: ViewMode) => void;
  setSearchQuery: (query: string) => void;
  setFilterExecutionType: (type: ExecutionType | 'all') => void;
  setFilterRole: (role: AgentRole | 'all') => void;
  setFilterStatus: (status: NodeStatus | 'all') => void;
  setFilterType: (type: NodeType | 'all') => void;

  // History Actions
  undo: () => void;
  redo: () => void;

  // Community & Canonical Topologies
  userTopologies: CanonicalArchetype[];
  publishTopology: (metadata: { name: string; description: string; category: string; tags: string[]; author: string }) => CanonicalArchetype;
  deleteUserTopology: (id: string) => void;
  loadTopologyDirect: (nodes: TopologyNode[], edges: TopologyEdge[]) => void;

  // Template / IO
  loadSampleTopology: (sampleId: string) => void;
  importCanvasData: (jsonStr: string) => boolean;
  setGraph: (nodes: TopologyNode[], edges: TopologyEdge[]) => void;
  resetGraph: () => void;

  // Computed Stats
  getStats: () => TopologyStats;

  // Live External Agent Sync
  liveSyncStatus: {
    connected: boolean;
    lastHeartbeat: number | null;
    activeAgents: number;
    desktopNotificationsEnabled: boolean;
    audioChimesEnabled: boolean;
  };
  setLiveSyncConnected: (connected: boolean) => void;
  setLiveSyncHeartbeat: (timestamp: number) => void;
  setDesktopNotificationsEnabled: (enabled: boolean) => void;
  setAudioChimesEnabled: (enabled: boolean) => void;

  // Shared Context Blackboard & Artifact Inspection
  sharedContext: SharedContextRepository;
  viewingArtifact: { artifact: ArtifactPayload; nodeId: string; nodeLabel: string } | null;
  writeSharedContext: (scope: 'global' | 'node', key: string, value: unknown, authorAgentId?: string, authorAgentRole?: string, nodeId?: string) => void;
  readSharedContext: (scope: 'global' | 'node', key?: string, nodeId?: string) => unknown;
  clearSharedContext: (scope: 'global' | 'node', key?: string, nodeId?: string) => void;
  setSharedContextRepository: (repo: SharedContextRepository) => void;
  setViewingArtifact: (item: { artifact: ArtifactPayload; nodeId: string; nodeLabel: string } | null) => void;
}

const defaultSample = SAMPLE_TOPOLOGIES[0];

const getInitialGraph = () => {
  const isMobile = typeof window !== 'undefined' && window.innerWidth < 768;
  const layoutDirection: 'LR' | 'TB' = isMobile ? 'TB' : 'LR';
  if (isMobile) {
    const positions = calculateDagreLayout(defaultSample.nodes, defaultSample.edges, 'TB');
    const nodes = defaultSample.nodes.map(n => ({
      ...n,
      position: positions[n.id] || n.position,
    }));
    return { nodes, edges: defaultSample.edges, layoutDirection };
  }
  return { nodes: defaultSample.nodes, edges: defaultSample.edges, layoutDirection };
};

const initialGraph = getInitialGraph();

const getInitialUserTopologies = (): CanonicalArchetype[] => {
  if (typeof window === 'undefined') return [];
  try {
    const raw = localStorage.getItem('topology_community_registry_v1');
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
};

export const useTopologyStore = create<TopologyStore>((set, get) => {
  const saveSnapshot = () => {
    const { nodes, edges, history } = get();
    // Keep max 20 snapshots
    const newHistory = [...history.slice(-19), { nodes: JSON.parse(JSON.stringify(nodes)), edges: JSON.parse(JSON.stringify(edges)) }];
    set({ history: newHistory, future: [] });
  };

  return {
    userTopologies: getInitialUserTopologies(),
    nodes: initialGraph.nodes,
    edges: initialGraph.edges,
    layoutDirection: initialGraph.layoutDirection,
    selectedNodeId: null,
    selectedNodeIds: [],
    hoveredNodeId: null,
    subgraphStack: [],
    theme: 'default',
    viewMode: '2d',
    lod: 'normal',
    searchQuery: '',
    liveSyncStatus: {
      connected: false,
      lastHeartbeat: null,
      activeAgents: 1,
      desktopNotificationsEnabled: typeof window !== 'undefined' && 'Notification' in window && Notification.permission === 'granted',
      audioChimesEnabled: true,
    },
    filterExecutionType: 'all',
    filterRole: 'all',
    filterStatus: 'all',
    filterType: 'all',

    isSimulating: false,
    simulationStep: 0,
    simulationBatches: [],

    // Multi-Agent Swarm State & Observability
    globalSquad: DEFAULT_AGENT_SQUAD,
    activityStream: [
      {
        id: 'init-1',
        timestamp: Date.now() - 12000,
        agentId: 'agent-sage',
        agentName: 'Sage',
        agentRole: 'Architect',
        agentColor: '#9334e6',
        agentAvatar: '🧠',
        nodeId: 'swarm-spec',
        nodeLabel: 'API Architecture & Security Contract',
        actionType: 'claimed_node',
        detail: 'Sage claimed lead role on API Architecture & Security Contract.',
      },
      {
        id: 'init-2',
        timestamp: Date.now() - 10000,
        agentId: 'agent-sentinel',
        agentName: 'Sentinel',
        agentRole: 'SecurityAnalyst',
        agentColor: '#ea4335',
        agentAvatar: '🛡️',
        nodeId: 'swarm-spec',
        nodeLabel: 'API Architecture & Security Contract',
        actionType: 'collaborated',
        detail: 'Sentinel joined in Debate & Consensus mode for auth boundary review.',
      },
      {
        id: 'init-3',
        timestamp: Date.now() - 8000,
        agentId: 'agent-apex',
        agentName: 'Apex',
        agentRole: 'CodeGenerator',
        agentColor: '#1a73e8',
        agentAvatar: '🤖',
        nodeId: 'swarm-backend',
        nodeLabel: 'Distributed Engine & Event Bus Core',
        actionType: 'claimed_node',
        detail: 'Apex standing by for async backend execution thread.',
      },
      {
        id: 'init-4',
        timestamp: Date.now() - 6000,
        agentId: 'agent-pixel',
        agentName: 'Pixel',
        agentRole: 'FrontendArchitect',
        agentColor: '#007b83',
        agentAvatar: '🎨',
        nodeId: 'swarm-frontend',
        nodeLabel: 'Elevated Fluid Workspace UI',
        actionType: 'claimed_node',
        detail: 'Pixel standing by for parallel async client UI thread.',
      },
    ],
    isCockpitOpen: false,
    activeFilterAgentId: null,

    // Shared Context Blackboard & Artifact Inspection Initial State
    sharedContext: {
      global: {
        system_architecture: {
          key: 'system_architecture',
          value: {
            paradigm: 'Autonomous Multi-Agent DAG Orchestration',
            contractVersion: '2.5.0',
            invariants: [
              'Zero circular causal dependencies (DAG validated)',
              'Artifact payload immutability across edges',
              'Explicit supervisor sign-off gate on high-criticality mutations'
            ]
          },
          authorAgentId: 'agent-sage',
          authorAgentRole: 'Architect',
          updatedAt: Date.now() - 3600000,
          scope: 'global'
        },
        security_policy: {
          key: 'security_policy',
          value: {
            authMethod: 'Local IPC / Bearer Bridge Token',
            sandboxStrict: true,
            maxConcurrentAutonomousWorkers: 6
          },
          authorAgentId: 'agent-sentinel',
          authorAgentRole: 'SecurityAnalyst',
          updatedAt: Date.now() - 1800000,
          scope: 'global'
        }
      },
      nodes: {
        'swarm-spec': {
          api_schema_spec: {
            key: 'api_schema_spec',
            value: {
              version: 'v2',
              endpoints: ['/api/topology/status', '/api/topology/plan', '/api/topology/context', '/api/topology/approve'],
              cors: 'origin-restricted'
            },
            authorAgentId: 'agent-sage',
            authorAgentRole: 'Architect',
            nodeId: 'swarm-spec',
            updatedAt: Date.now() - 900000,
            scope: 'node'
          }
        }
      }
    },
    viewingArtifact: null,

    history: [],
    future: [],

    findSmartConnectTarget: (pos, type = 'task') => {
      const { nodes, selectedNodeId } = get();
      if (nodes.length === 0) return null;

      // 1. If a node is selected, that's the primary candidate
      if (selectedNodeId) {
        const sel = nodes.find(n => n.id === selectedNodeId);
        if (sel) return sel;
      }

      // 2. Find upstream candidates to the left of pos.x
      const leftCandidates = nodes.filter(n => n.position.x < pos.x + 40);
      if (leftCandidates.length > 0) {
        // Find one with closest distance
        let closest = leftCandidates[0];
        let minDist = Infinity;
        for (const cand of leftCandidates) {
          const dx = pos.x - cand.position.x;
          const dy = pos.y - cand.position.y;
          const dist = Math.sqrt(dx * dx + dy * dy);
          if (dist < minDist) {
            minDist = dist;
            closest = cand;
          }
        }
        return closest;
      }

      // 3. Fallback: most recent non-milestone node
      const nonMilestone = [...nodes].reverse().find(n => n.type !== 'milestone');
      return nonMilestone || nodes[nodes.length - 1];
    },

    addNode: (partial = {}, options = {}) => {
      saveSnapshot();
      const currentNodes = get().nodes;
      const count = currentNodes.length + 1;
      const id = `node-${Date.now().toString(36)}-${Math.random().toString(36).substring(2, 6)}`;
      
      const nodePos = partial.position || {
        x: (currentNodes.length % 4) * 320 + 80,
        y: Math.floor(currentNodes.length / 4) * 200 + 100,
      };

      const newNode: TopologyNode = {
        id,
        type: partial.type || 'task',
        label: partial.label || `Planned Task ${count}`,
        description: partial.description || 'Describe objective, scope, and expected outcome...',
        status: partial.status || 'draft',
        priority: partial.priority || 'medium',
        tags: partial.tags || ['agent-plan'],
        context: {
          executionType: partial.context?.executionType || (partial.type === 'decision' ? 'conditional_router' : 'autonomous_agent'),
          modelEngine: partial.context?.modelEngine || (partial.type === 'decision' ? 'script-runner' : 'gemini-2.5-pro'),
          role: partial.context?.role || 'GeneralAgent',
          promptTemplate: partial.context?.promptTemplate || 'Execute task steps according to protocol.',
          toolsRequired: partial.context?.toolsRequired || ['write_file', 'ast_analyzer'],
          inputArtifacts: partial.context?.inputArtifacts || [],
          outputArtifacts: partial.context?.outputArtifacts || [],
          validationCriteria: partial.context?.validationCriteria || 'Pass all checks.',
          fallbackAction: partial.context?.fallbackAction || 'Retry or alert supervisor.',
          estimatedMinutes: partial.context?.estimatedMinutes || 15,
          telemetry: {
            state: 'idle',
            terminalLogs: ['Execution engine initialized. Ready for dispatch.'],
            lastUpdated: Date.now(),
          },
        },
        position: nodePos,
        subgraph: partial.subgraph,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      };

      set({ 
        nodes: [...currentNodes, newNode],
        selectedNodeId: newNode.id 
      });

      // Smart Auto-Connect logic
      if (options.autoConnect !== false) {
        let targetCandidate: TopologyNode | null = null;
        if (options.targetId) {
          targetCandidate = currentNodes.find(n => n.id === options.targetId) || null;
        } else {
          targetCandidate = get().findSmartConnectTarget(nodePos, newNode.type);
        }

        if (targetCandidate && targetCandidate.id !== newNode.id) {
          let edgeType: EdgeType = 'depends_on';
          let edgeLabel = 'dependency';

          if (newNode.type === 'artifact') {
            edgeType = 'produces';
            edgeLabel = 'produces';
          } else if (targetCandidate.type === 'goal' && newNode.type === 'task') {
            edgeType = 'subtask';
            edgeLabel = 'subtask';
          }

          get().connectNodes(targetCandidate.id, newNode.id, edgeType, edgeLabel);
        }
      }

      return newNode;
    },

    enterSubgraph: (nodeId) => {
      const { nodes, edges, subgraphStack } = get();
      const parentNode = nodes.find(n => n.id === nodeId);
      if (!parentNode) return;

      saveSnapshot();

      // Push current topology to stack
      const newFrame: SubgraphStackFrame = {
        parentId: parentNode.id,
        parentLabel: parentNode.label,
        nodes: JSON.parse(JSON.stringify(nodes)),
        edges: JSON.parse(JSON.stringify(edges)),
      };

      if (parentNode.subgraph && parentNode.subgraph.nodes.length > 0) {
        set({
          subgraphStack: [...subgraphStack, newFrame],
          nodes: parentNode.subgraph.nodes,
          edges: parentNode.subgraph.edges,
          selectedNodeId: null,
        });
      } else {
        // Seed new empty/template subgraph
        const childNodes: TopologyNode[] = [
          {
            id: `sub-start-${Date.now().toString(36)}`,
            type: 'task',
            label: `Sub-routine: ${parentNode.label.slice(0, 20)}`,
            description: `Decomposed micro-task executing within ${parentNode.label}`,
            status: 'ready',
            priority: 'high',
            tags: ['subgraph', 'micro-task'],
            position: { x: 100, y: 150 },
            context: {
              role: parentNode.context.role,
              promptTemplate: `Execute detailed sub-routine for ${parentNode.label}`,
              toolsRequired: parentNode.context.toolsRequired,
              inputArtifacts: parentNode.context.inputArtifacts,
              outputArtifacts: parentNode.context.outputArtifacts,
              validationCriteria: 'Micro-step verified',
            },
            createdAt: Date.now(),
            updatedAt: Date.now(),
          },
          {
            id: `sub-verify-${Date.now().toString(36)}`,
            type: 'milestone',
            label: `Verify & Return: ${parentNode.label.slice(0, 16)}`,
            description: `Verify outputs and report success back to parent topology`,
            status: 'pending',
            priority: 'medium',
            tags: ['subgraph', 'verification'],
            position: { x: 450, y: 150 },
            context: {
              role: 'TestAuditor',
              promptTemplate: 'Validate sub-routine outputs against parent acceptance criteria.',
              toolsRequired: [],
              inputArtifacts: [],
              outputArtifacts: [],
              validationCriteria: 'All outputs conforming',
            },
            createdAt: Date.now(),
            updatedAt: Date.now(),
          },
        ];

        const childEdges: TopologyEdge[] = [
          {
            id: `sub-edge-${Date.now().toString(36)}`,
            source: childNodes[0].id,
            target: childNodes[1].id,
            type: 'depends_on',
            label: 'validates',
          },
        ];

        set({
          subgraphStack: [...subgraphStack, newFrame],
          nodes: childNodes,
          edges: childEdges,
          selectedNodeId: null,
        });
      }
    },

    exitSubgraph: () => {
      const { subgraphStack, nodes: currentNodes, edges: currentEdges } = get();
      if (subgraphStack.length === 0) return;

      saveSnapshot();
      const topFrame = subgraphStack[subgraphStack.length - 1];
      const remainingStack = subgraphStack.slice(0, -1);

      // Save current subgraph back into parent node
      const restoredNodes = topFrame.nodes.map(n => {
        if (n.id === topFrame.parentId) {
          return {
            ...n,
            subgraph: {
              id: `subgraph-${n.id}`,
              label: n.label,
              nodes: currentNodes,
              edges: currentEdges,
            },
          };
        }
        return n;
      });

      set({
        subgraphStack: remainingStack,
        nodes: restoredNodes,
        edges: topFrame.edges,
        selectedNodeId: topFrame.parentId,
      });
    },

    navigateToBreadcrumb: (index) => {
      const { subgraphStack } = get();
      // If navigating to root
      if (index === -1) {
        while (get().subgraphStack.length > 0) {
          get().exitSubgraph();
        }
        return;
      }

      // Pop down to index
      while (get().subgraphStack.length > index + 1) {
        get().exitSubgraph();
      }
    },

    runAutonomousAgent: (nodeId) => {
      const node = get().nodes.find(n => n.id === nodeId);
      if (!node) return;

      const tools = node.context.toolsRequired.length > 0 ? node.context.toolsRequired[0] : 'ast_analyzer';
      const execType = node.context.executionType || 'autonomous_agent';
      const engine = node.context.modelEngine || 'gemini-2.5-pro';
      const engineLabel = execType === 'automated_script' ? `Script Engine [${engine}]` :
                          execType === 'human_operator' ? `Human Review Gate` :
                          `Autonomous Agent [${engine}]`;

      // Step 1: Thinking / Planning
      get().updateNode(nodeId, {
        status: 'in_progress',
        context: {
          ...node.context,
          telemetry: {
            state: 'thinking',
            activeTool: undefined,
            liveThought: `${engineLabel} synthesizing execution plan for "${node.label}"...`,
            terminalLogs: [
              `[00:01] Execution dispatch initiated for node ${nodeId}`,
              `[00:02] Engine active: ${engineLabel}`,
              `[00:03] Bound input artifacts: ${node.context.inputArtifacts.join(', ') || 'None'}`,
              `[00:04] Tool pipeline: ${node.context.toolsRequired.join(', ') || 'write_file, ast_analyzer'}`,
            ],
            lastUpdated: Date.now(),
          },
        },
      });

      // Step 2: Executing Tool
      setTimeout(() => {
        const currentNode = get().nodes.find(n => n.id === nodeId);
        if (!currentNode) return;
        const currentLogs = currentNode.context.telemetry?.terminalLogs || [];

        get().updateNode(nodeId, {
          context: {
            ...currentNode.context,
            telemetry: {
              state: 'executing_tool',
              activeTool: tools,
              liveThought: `Executing tool: ${tools} with input context...`,
              terminalLogs: [
                ...currentLogs,
                `[00:05] Calling tool: ${tools}()`,
                `[00:07] Executing payload on execution thread`,
                `[00:08] Tool returned exit code 0: 100% OK`,
              ],
              lastUpdated: Date.now(),
            },
          },
        });
      }, 700);

      // Step 3: Validating
      setTimeout(() => {
        const currentNode = get().nodes.find(n => n.id === nodeId);
        if (!currentNode) return;
        const currentLogs = currentNode.context.telemetry?.terminalLogs || [];

        // Check if Human-in-the-loop approval is mandated
        if (currentNode.context.requiresHumanApproval && currentNode.context.approvalStatus !== 'approved') {
          get().updateNode(nodeId, {
            status: 'in_progress',
            context: {
              ...currentNode.context,
              approvalStatus: 'pending',
              telemetry: {
                state: 'validating',
                activeTool: undefined,
                liveThought: `Validation passed. Execution paused at Human Review Gate for supervisor sign-off.`,
                terminalLogs: [
                  ...currentLogs,
                  `[00:10] Running validation check: ${currentNode.context.validationCriteria || 'Standard Invariants'}`,
                  `[00:11] Pre-validation verified. Zero regressions.`,
                  `[00:12] HITL REVIEW GATE ACTIVE: Pausing workflow for supervisor sign-off.`,
                ],
                lastUpdated: Date.now(),
              },
            },
          });
          return; // Pause execution here until approveNode is triggered
        }

        get().updateNode(nodeId, {
          context: {
            ...currentNode.context,
            telemetry: {
              state: 'validating',
              activeTool: undefined,
              liveThought: `Validating outputs against acceptance criteria: "${currentNode.context.validationCriteria}"...`,
              terminalLogs: [
                ...currentLogs,
                `[00:10] Running validation check: ${currentNode.context.validationCriteria || 'Standard Invariants'}`,
                `[00:11] Invariants verified. Zero regressions.`,
              ],
              lastUpdated: Date.now(),
            },
          },
        });
      }, 1400);

      // Step 4: Completed & Artifact Propagation
      setTimeout(() => {
        const currentNode = get().nodes.find(n => n.id === nodeId);
        if (!currentNode) return;
        if (currentNode.context.requiresHumanApproval && currentNode.context.approvalStatus !== 'approved') {
          return; // Still waiting for approval
        }

        const currentLogs = currentNode.context.telemetry?.terminalLogs || [];

        // Synthesize real output artifact payloads
        const outputs = currentNode.context.outputArtifacts || [];
        const generatedPayloads: Record<string, ArtifactPayload> = {
          ...(currentNode.context.artifactPayloads || {})
        };

        if (outputs.length === 0) {
          const defaultArtifactName = `${currentNode.label.toLowerCase().replace(/[^a-z0-9]/g, '_')}_output.json`;
          generatedPayloads[defaultArtifactName] = createSyntheticArtifactPayload(defaultArtifactName, currentNode.context.role, currentNode.label);
        } else {
          outputs.forEach(artName => {
            if (!generatedPayloads[artName]) {
              generatedPayloads[artName] = createSyntheticArtifactPayload(artName, currentNode.context.role, currentNode.label);
            }
          });
        }

        // Propagate artifacts down outgoing edges
        const { edges, nodes } = get();
        const outgoingEdges = edges.filter(e => e.source === nodeId);
        const downstreamTargetIds = new Set(outgoingEdges.map(e => e.target));

        const updatedNodes = nodes.map(n => {
          if (n.id === nodeId) {
            return {
              ...n,
              status: 'completed' as NodeStatus,
              context: {
                ...n.context,
                artifactPayloads: generatedPayloads,
                telemetry: {
                  state: 'completed' as const,
                  activeTool: undefined,
                  liveThought: `Autonomous work unit completed successfully!`,
                  terminalLogs: [
                    ...currentLogs,
                    `[00:14] Emitting output artifacts: ${Object.keys(generatedPayloads).join(', ')}`,
                    `[00:15] Data payloads packaged (${Object.values(generatedPayloads).reduce((acc, p) => acc + p.sizeBytes, 0)} bytes).`,
                    `[00:16] Downstream causal dependencies unblocked.`,
                  ],
                  lastUpdated: Date.now(),
                },
              },
            };
          }

          if (downstreamTargetIds.has(n.id)) {
            // Receive artifact payloads into input context
            const incomingPayloads = {
              ...(n.context.artifactPayloads || {}),
              ...generatedPayloads,
            };

            // Check if all upstream nodes are completed
            const upEdges = edges.filter(e => e.target === n.id);
            const allUpCompleted = upEdges.every(e => {
              if (e.source === nodeId) return true;
              const srcNode = nodes.find(sn => sn.id === e.source);
              return srcNode?.status === 'completed';
            });

            return {
              ...n,
              status: allUpCompleted && (n.status === 'pending' || n.status === 'blocked') ? ('ready' as NodeStatus) : n.status,
              context: {
                ...n.context,
                artifactPayloads: incomingPayloads,
              },
            };
          }

          return n;
        });

        // Update edges to indicate data payload transfer
        const updatedEdges = edges.map(e => {
          if (e.source === nodeId) {
            return {
              ...e,
              animated: true,
              dataPayloadPassed: Object.keys(generatedPayloads),
            };
          }
          return e;
        });

        set({
          nodes: updatedNodes,
          edges: updatedEdges,
        });
      }, 2100);
    },

    getCoherenceReport: () => {
      const { nodes, edges } = get();
      return validateGraphCoherence(nodes, edges);
    },

    applyAutoFix: (issueId) => {
      const { nodes, edges } = get();
      const report = validateGraphCoherence(nodes, edges);
      const issue = report.issues.find(i => i.id === issueId);
      if (!issue) return;

      saveSnapshot();

      if (issue.autoFixType === 'CONNECT_ORPHAN') {
        const orphanId = issue.nodeIds[0];
        const otherNodes = nodes.filter(n => n.id !== orphanId);
        if (otherNodes.length > 0) {
          // Connect to the latest task or goal
          const target = otherNodes.find(n => n.type === 'goal') || otherNodes[0];
          get().connectNodes(target.id, orphanId, 'depends_on', 'prerequisite');
        }
      } else if (issue.autoFixType === 'BREAK_CYCLE') {
        // Remove the latest edge that participates in the cycle
        const cycleNodesSet = new Set(issue.nodeIds);
        const cycleEdge = edges.find(e => cycleNodesSet.has(e.source) && cycleNodesSet.has(e.target));
        if (cycleEdge) {
          get().removeEdge(cycleEdge.id);
        }
      } else if (issue.autoFixType === 'ADD_TERMINAL_MILESTONE') {
        // Create a milestone and link open leaves
        const maxX = Math.max(...nodes.map(n => n.position.x), 500);
        const avgY = nodes.reduce((acc, n) => acc + n.position.y, 0) / nodes.length;

        const milestoneNode = get().addNode({
          type: 'milestone',
          label: 'System Deliverable & Verification Gate',
          description: 'Final consolidation gate confirming all subtasks and artifacts are complete.',
          status: 'pending',
          priority: 'critical',
          position: { x: maxX + 360, y: avgY },
        }, { autoConnect: false });

        issue.nodeIds.forEach(leafId => {
          get().connectNodes(leafId, milestoneNode.id, 'depends_on', 'delivers');
        });
      } else if (issue.autoFixType === 'ADD_STOPPING_CONDITION') {
        const targetNodeId = issue.nodeIds[0];
        const targetNode = nodes.find(n => n.id === targetNodeId);
        if (targetNode) {
          get().updateNode(targetNodeId, {
            context: {
              ...targetNode.context,
              stoppingCondition: {
                expression: 'iteration >= 3 || accuracy >= 0.95',
                description: 'Terminate recursive loop once max 3 iterations or 95% target reached.',
                maxIterations: 3,
                isRecursive: true,
              },
            },
          });
        }
      } else if (issue.autoFixType === 'SYNTHESIZE_MISSING_ARTIFACT') {
        const consumerNodeId = issue.nodeIds[0];
        const consumer = nodes.find(n => n.id === consumerNodeId);
        if (consumer) {
          const missingArt = consumer.context.inputArtifacts[0] || 'spec.json';
          const producer = get().addNode({
            type: 'task',
            label: `Generate ${missingArt}`,
            description: `Precursor action step producing ${missingArt} for ${consumer.label}`,
            status: 'ready',
            position: { x: consumer.position.x - 340, y: consumer.position.y },
            context: {
              role: 'CodeGenerator',
              promptTemplate: `Synthesize ${missingArt} data contract.`,
              toolsRequired: ['write_file'],
              inputArtifacts: [],
              outputArtifacts: [missingArt],
              validationCriteria: `${missingArt} exists and matches schema`,
            },
          }, { autoConnect: false });

          get().connectNodes(producer.id, consumer.id, 'produces', missingArt);
        }
      }
    },

    updateNode: (id, updates) => {
      saveSnapshot();
      set({
        nodes: get().nodes.map(node => {
          if (node.id === id) {
            return {
              ...node,
              ...updates,
              context: updates.context ? { ...node.context, ...updates.context } : node.context,
              updatedAt: Date.now(),
            };
          }
          return node;
        }),
      });
    },

    deleteNode: (id) => {
      saveSnapshot();
      const { nodes, edges, selectedNodeId, selectedNodeIds } = get();
      const remainingNodes = nodes.filter(n => n.id !== id);
      const remainingEdges = edges.filter(e => e.source !== id && e.target !== id);

      set({
        nodes: remainingNodes,
        edges: remainingEdges,
        selectedNodeId: selectedNodeId === id ? null : selectedNodeId,
        selectedNodeIds: selectedNodeIds.filter(nid => nid !== id),
      });
    },

    connectNodes: (sourceId, targetId, type = 'depends_on', label, condition) => {
      if (sourceId === targetId) {
        return { success: false, error: 'Self-referential dependencies are not permitted.' };
      }

      const { nodes, edges } = get();
      const existing = edges.find(e => e.source === sourceId && e.target === targetId);
      if (existing) {
        return { success: false, error: 'Dependency edge already exists between these nodes.' };
      }

      const newEdge: TopologyEdge = {
        id: `edge-${Date.now().toString(36)}-${Math.random().toString(36).substring(2, 6)}`,
        source: sourceId,
        target: targetId,
        type,
        label,
        condition,
        animated: type === 'depends_on',
      };

      const candidateEdges = [...edges, newEdge];
      const cycleCheck = detectCycles(nodes, candidateEdges);

      if (cycleCheck.hasCycle) {
        return { 
          success: false, 
          error: 'Connection rejected: Circular dependency detected in the plan.' 
        };
      }

      saveSnapshot();
      set({ edges: candidateEdges });
      return { success: true };
    },

    removeEdge: (edgeId) => {
      saveSnapshot();
      set({ edges: get().edges.filter(e => e.id !== edgeId) });
    },

    selectNode: (id) => {
      set({ 
        selectedNodeId: id,
        selectedNodeIds: id ? [id] : [],
      });
    },

    setSelectedNodeIds: (ids) => {
      set({
        selectedNodeIds: ids,
        selectedNodeId: ids.length === 1 ? ids[0] : (ids.length > 0 ? ids[0] : null),
      });
    },

    toggleNodeSelection: (id, multi = false) => {
      const { selectedNodeIds } = get();
      if (!multi) {
        set({
          selectedNodeId: id,
          selectedNodeIds: id ? [id] : [],
        });
      } else {
        const exists = selectedNodeIds.includes(id);
        const next = exists
          ? selectedNodeIds.filter(nid => nid !== id)
          : [...selectedNodeIds, id];
        set({
          selectedNodeIds: next,
          selectedNodeId: next.length === 1 ? next[0] : (next.length > 0 ? next[0] : null),
        });
      }
    },

    clearNodeSelection: () => {
      set({ selectedNodeId: null, selectedNodeIds: [] });
    },

    setLod: (lod) => set({ lod }),

    approveNode: (nodeId, notes) => {
      const node = get().nodes.find(n => n.id === nodeId);
      if (!node) return;
      saveSnapshot();

      const currentLogs = node.context.telemetry?.terminalLogs || [];
      const outputs = node.context.outputArtifacts || [];
      const generatedPayloads: Record<string, ArtifactPayload> = {
        ...(node.context.artifactPayloads || {})
      };

      if (outputs.length === 0) {
        const defaultName = `${node.label.toLowerCase().replace(/[^a-z0-9]/g, '_')}_output.json`;
        generatedPayloads[defaultName] = createSyntheticArtifactPayload(defaultName, node.context.role, node.label);
      } else {
        outputs.forEach(artName => {
          if (!generatedPayloads[artName]) {
            generatedPayloads[artName] = createSyntheticArtifactPayload(artName, node.context.role, node.label);
          }
        });
      }

      const { edges, nodes } = get();
      const outgoingEdges = edges.filter(e => e.source === nodeId);
      const downstreamTargetIds = new Set(outgoingEdges.map(e => e.target));

      const updatedNodes = nodes.map(n => {
        if (n.id === nodeId) {
          return {
            ...n,
            status: 'completed' as NodeStatus,
            context: {
              ...n.context,
              approvalStatus: 'approved' as const,
              approvalNotes: notes || 'Approved by supervisor',
              artifactPayloads: generatedPayloads,
              telemetry: {
                state: 'completed' as const,
                activeTool: undefined,
                liveThought: `Node execution signed off by supervisor.`,
                terminalLogs: [
                  ...currentLogs,
                  `[HITL SIGN-OFF] Human supervisor verified and approved execution step.`,
                  ...(notes ? [`[SUPERVISOR NOTE] ${notes}`] : []),
                  `[00:14] Emitting output artifacts: ${Object.keys(generatedPayloads).join(', ')}`,
                  `[00:15] Downstream causal dependencies unblocked.`,
                ],
                lastUpdated: Date.now(),
              },
            },
          };
        }

        if (downstreamTargetIds.has(n.id)) {
          const incomingPayloads = {
            ...(n.context.artifactPayloads || {}),
            ...generatedPayloads,
          };
          const upEdges = edges.filter(e => e.target === n.id);
          const allUpCompleted = upEdges.every(e => {
            if (e.source === nodeId) return true;
            const srcNode = nodes.find(sn => sn.id === e.source);
            return srcNode?.status === 'completed';
          });

          return {
            ...n,
            status: allUpCompleted && (n.status === 'pending' || n.status === 'blocked') ? ('ready' as NodeStatus) : n.status,
            context: {
              ...n.context,
              artifactPayloads: incomingPayloads,
            },
          };
        }

        return n;
      });

      const updatedEdges = edges.map(e => {
        if (e.source === nodeId) {
          return {
            ...e,
            animated: true,
            dataPayloadPassed: Object.keys(generatedPayloads),
          };
        }
        return e;
      });

      set({ nodes: updatedNodes, edges: updatedEdges });

      // Notify external agent bridge of human decision
      if (typeof window !== 'undefined') {
        fetch('/api/topology/approve', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ nodeId, decision: 'approved', notes: notes || 'Approved by supervisor' })
        }).catch(() => {});
      }
    },

    rejectNode: (nodeId, notes) => {
      const node = get().nodes.find(n => n.id === nodeId);
      if (!node) return;
      saveSnapshot();

      const currentLogs = node.context.telemetry?.terminalLogs || [];
      get().updateNode(nodeId, {
        status: 'blocked',
        context: {
          ...node.context,
          approvalStatus: 'rejected',
          approvalNotes: notes || 'Supervisor requested revision',
          telemetry: {
            state: 'error',
            activeTool: undefined,
            liveThought: `Execution rejected by supervisor: ${notes || 'Revision required'}`,
            terminalLogs: [
              ...currentLogs,
              `[HITL REJECTION] Human supervisor rejected step outputs.`,
              ...(notes ? [`[REASON] ${notes}`] : []),
              `Execution halted. Awaiting human or agent remediation.`,
            ],
            lastUpdated: Date.now(),
          },
        },
      });

      // Notify external agent bridge of human decision
      if (typeof window !== 'undefined') {
        fetch('/api/topology/approve', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ nodeId, decision: 'rejected', notes: notes || 'Supervisor requested revision' })
        }).catch(() => {});
      }
    },

    toggleApprovalRequired: (nodeId) => {
      const node = get().nodes.find(n => n.id === nodeId);
      if (!node) return;
      saveSnapshot();
      const current = !!node.context.requiresHumanApproval;
      get().updateNode(nodeId, {
        context: {
          ...node.context,
          requiresHumanApproval: !current,
          approvalStatus: !current ? 'pending' : undefined,
        },
      });
    },

    setViewingArtifact: (item) => set({ viewingArtifact: item }),

    setSharedContextRepository: (repo) => set({ sharedContext: repo }),

    writeSharedContext: (scope, key, value, authorAgentId = 'agent-supervisor', authorAgentRole = 'Supervisor', nodeId) => {
      const entry: SharedContextEntry = {
        key,
        value,
        authorAgentId,
        authorAgentRole,
        nodeId: scope === 'node' ? nodeId : undefined,
        updatedAt: Date.now(),
        scope,
      };

      set((state) => {
        const next: SharedContextRepository = {
          global: { ...state.sharedContext.global },
          nodes: { ...state.sharedContext.nodes },
        };

        if (scope === 'global') {
          next.global[key] = entry;
        } else if (nodeId) {
          next.nodes[nodeId] = {
            ...(next.nodes[nodeId] || {}),
            [key]: entry,
          };
        }
        return { sharedContext: next };
      });

      // Synchronize with backend bridge in background (fire-and-forget with catch)
      if (typeof window !== 'undefined') {
        fetch('/api/topology/context', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ scope, key, value, authorAgentId, authorAgentRole, nodeId }),
        }).catch(() => {});
      }
    },

    readSharedContext: (scope, key, nodeId) => {
      const { sharedContext } = get();
      if (scope === 'global') {
        if (key) return sharedContext.global[key]?.value;
        return sharedContext.global;
      } else if (nodeId) {
        const nodeCtx = sharedContext.nodes[nodeId] || {};
        if (key) return nodeCtx[key]?.value;
        return nodeCtx;
      }
      return undefined;
    },

    clearSharedContext: (scope, key, nodeId) => {
      set((state) => {
        const next: SharedContextRepository = {
          global: { ...state.sharedContext.global },
          nodes: { ...state.sharedContext.nodes },
        };

        if (scope === 'global') {
          if (key) {
            delete next.global[key];
          } else {
            next.global = {};
          }
        } else if (nodeId && next.nodes[nodeId]) {
          if (key) {
            delete next.nodes[nodeId][key];
          } else {
            delete next.nodes[nodeId];
          }
        }
        return { sharedContext: next };
      });
    },

    evaluateDecisionBranch: (nodeId, conditionResult) => {
      const node = get().nodes.find(n => n.id === nodeId);
      if (!node) return;
      saveSnapshot();

      const currentLogs = node.context.telemetry?.terminalLogs || [];
      const conditionStr = conditionResult ? 'true' : 'false';

      const { edges, nodes } = get();
      const outgoingEdges = edges.filter(e => e.source === nodeId);

      const updatedEdges = edges.map(e => {
        if (e.source === nodeId) {
          const edgeMatches = !e.condition || e.condition === 'always' || e.condition === conditionStr;
          return {
            ...e,
            animated: edgeMatches,
          };
        }
        return e;
      });

      const activeTargets = new Set(
        outgoingEdges
          .filter(e => !e.condition || e.condition === 'always' || e.condition === conditionStr)
          .map(e => e.target)
      );

      const updatedNodes = nodes.map(n => {
        if (n.id === nodeId) {
          return {
            ...n,
            status: 'completed' as NodeStatus,
            context: {
              ...n.context,
              decisionCondition: {
                expression: n.context.decisionCondition?.expression || 'validation_score >= threshold',
                evaluatedResult: conditionResult,
                evaluatedAt: Date.now(),
              },
              telemetry: {
                state: 'completed' as const,
                activeTool: undefined,
                liveThought: `Decision evaluated to [${conditionResult ? 'TRUE' : 'FALSE'}]. Activating branch.`,
                terminalLogs: [
                  ...currentLogs,
                  `[DECISION EVALUATED] Expression returned: ${conditionResult ? 'TRUE' : 'FALSE'}`,
                  `Activating downstream branch edges matching condition='${conditionStr}'.`,
                ],
                lastUpdated: Date.now(),
              },
            },
          };
        }

        if (activeTargets.has(n.id)) {
          return {
            ...n,
            status: (n.status === 'pending' || n.status === 'blocked') ? ('ready' as NodeStatus) : n.status,
          };
        }

        return n;
      });

      set({ nodes: updatedNodes, edges: updatedEdges });
    },

    bundleSelectedIntoSubgraph: (label) => {
      const { selectedNodeIds, nodes, edges } = get();
      if (selectedNodeIds.length < 2) return;
      saveSnapshot();

      const selectedIdSet = new Set(selectedNodeIds);
      const selectedNodes = nodes.filter(n => selectedIdSet.has(n.id));
      const internalEdges = edges.filter(e => selectedIdSet.has(e.source) && selectedIdSet.has(e.target));

      const avgX = selectedNodes.reduce((acc, n) => acc + n.position.x, 0) / selectedNodes.length;
      const avgY = selectedNodes.reduce((acc, n) => acc + n.position.y, 0) / selectedNodes.length;

      const bundleId = `bundle-${Date.now().toString(36)}`;
      const bundleLabel = label || `Composite (${selectedNodes.length} Nodes)`;

      const bundledNode: TopologyNode = {
        id: bundleId,
        type: 'task',
        label: bundleLabel,
        description: `Nested modular composite containing ${selectedNodes.length} clustered topology units.`,
        status: 'ready',
        priority: 'high',
        tags: ['subgraph', 'composite'],
        position: { x: avgX, y: avgY },
        createdAt: Date.now(),
        updatedAt: Date.now(),
        context: {
          role: 'Architect',
          promptTemplate: `Execute composite subsystem DAG: ${bundleLabel}`,
          toolsRequired: ['subgraph_orchestrator'],
          inputArtifacts: [],
          outputArtifacts: [`${bundleLabel.toLowerCase().replace(/[^a-z0-9]/g, '_')}.json`],
          validationCriteria: 'All nested child nodes executed with zero defects',
        },
        subgraph: {
          id: `sub-${bundleId}`,
          label: bundleLabel,
          nodes: selectedNodes,
          edges: internalEdges,
        },
      };

      const remainingEdges: TopologyEdge[] = [];
      const seenEdgeKeys = new Set<string>();

      edges.forEach(e => {
        const srcIn = selectedIdSet.has(e.source);
        const tgtIn = selectedIdSet.has(e.target);

        if (srcIn && tgtIn) {
          // internal edge
          return;
        } else if (!srcIn && tgtIn) {
          const key = `${e.source}->${bundleId}`;
          if (!seenEdgeKeys.has(key)) {
            seenEdgeKeys.add(key);
            remainingEdges.push({
              ...e,
              target: bundleId,
            });
          }
        } else if (srcIn && !tgtIn) {
          const key = `${bundleId}->${e.target}`;
          if (!seenEdgeKeys.has(key)) {
            seenEdgeKeys.add(key);
            remainingEdges.push({
              ...e,
              source: bundleId,
            });
          }
        } else {
          remainingEdges.push(e);
        }
      });

      const remainingNodes = nodes.filter(n => !selectedIdSet.has(n.id));

      set({
        nodes: [...remainingNodes, bundledNode],
        edges: remainingEdges,
        selectedNodeId: bundleId,
        selectedNodeIds: [bundleId],
      });
    },

    alignSelectedNodes: (direction) => {
      const { selectedNodeIds, nodes } = get();
      if (selectedNodeIds.length < 2) return;
      saveSnapshot();

      const selectedIdSet = new Set(selectedNodeIds);
      const selectedNodes = nodes.filter(n => selectedIdSet.has(n.id));

      if (direction === 'horizontal') {
        const avgY = selectedNodes.reduce((acc, n) => acc + n.position.y, 0) / selectedNodes.length;
        const sorted = [...selectedNodes].sort((a, b) => a.position.x - b.position.x);
        const minX = sorted[0].position.x;

        const newPosMap: Record<string, { x: number; y: number }> = {};
        sorted.forEach((n, idx) => {
          newPosMap[n.id] = { x: minX + idx * 340, y: avgY };
        });

        set({
          nodes: nodes.map(n => (newPosMap[n.id] ? { ...n, position: newPosMap[n.id] } : n)),
        });
      } else {
        const avgX = selectedNodes.reduce((acc, n) => acc + n.position.x, 0) / selectedNodes.length;
        const sorted = [...selectedNodes].sort((a, b) => a.position.y - b.position.y);
        const minY = sorted[0].position.y;

        const newPosMap: Record<string, { x: number; y: number }> = {};
        sorted.forEach((n, idx) => {
          newPosMap[n.id] = { x: avgX, y: minY + idx * 170 };
        });

        set({
          nodes: nodes.map(n => (newPosMap[n.id] ? { ...n, position: newPosMap[n.id] } : n)),
        });
      }
    },

    batchSetStatus: (status) => {
      const { selectedNodeIds, nodes } = get();
      if (selectedNodeIds.length === 0) return;
      saveSnapshot();

      const idSet = new Set(selectedNodeIds);
      set({
        nodes: nodes.map(n => (idSet.has(n.id) ? { ...n, status, updatedAt: Date.now() } : n)),
      });
    },

    batchDeleteNodes: () => {
      const { selectedNodeIds, nodes, edges } = get();
      if (selectedNodeIds.length === 0) return;
      saveSnapshot();

      const idSet = new Set(selectedNodeIds);
      set({
        nodes: nodes.filter(n => !idSet.has(n.id)),
        edges: edges.filter(e => !idSet.has(e.source) && !idSet.has(e.target)),
        selectedNodeId: null,
        selectedNodeIds: [],
      });
    },

    setHoveredNode: (id) => {
      set({ hoveredNodeId: id });
    },

    branchChildNode: (parentId) => {
      const parent = get().nodes.find(n => n.id === parentId);
      const parentPos = parent ? parent.position : { x: 100, y: 100 };
      const isVertical = get().layoutDirection === 'TB';
      
      const child = get().addNode({
        type: 'task',
        label: `Subtask of ${parent ? parent.label.slice(0, 18) : 'Task'}`,
        description: `Decomposed action step following ${parent ? parent.label : 'prerequisite'}.`,
        status: 'pending',
        position: isVertical
          ? { x: parentPos.x + (Math.random() * 60 - 30), y: parentPos.y + 190 }
          : { x: parentPos.x + 340, y: parentPos.y + (Math.random() * 80 - 40) },
      });

      get().connectNodes(parentId, child.id, 'depends_on', 'prerequisite');
      return child;
    },

    createSiblingNode: (referenceId) => {
      const ref = get().nodes.find(n => n.id === referenceId);
      const refPos = ref ? ref.position : { x: 100, y: 100 };
      const isVertical = get().layoutDirection === 'TB';

      const sibling = get().addNode({
        type: ref ? ref.type : 'task',
        label: `Parallel ${ref ? ref.type : 'Task'}`,
        description: 'Parallel stream of execution for the agent.',
        status: 'ready',
        position: isVertical
          ? { x: refPos.x + 310, y: refPos.y }
          : { x: refPos.x, y: refPos.y + 160 },
      });

      return sibling;
    },

    applyDagreLayout: (direction) => {
      saveSnapshot();
      const { nodes, edges, layoutDirection } = get();
      const targetDir = direction || layoutDirection || 'LR';
      const positions = calculateDagreLayout(nodes, edges, targetDir);

      set({
        layoutDirection: targetDir,
        nodes: nodes.map(n => ({
          ...n,
          position: positions[n.id] || n.position,
        })),
      });
    },

    setLayoutDirection: (dir: 'LR' | 'TB') => {
      const current = get().layoutDirection;
      if (current === dir) return;
      get().applyDagreLayout(dir);
    },

    toggleLayoutDirection: () => {
      const next = get().layoutDirection === 'LR' ? 'TB' : 'LR';
      get().applyDagreLayout(next);
    },

    startSimulation: () => {
      const { nodes, edges } = get();
      const { batches, isCyclic } = getTopologicalBatches(nodes, edges);
      if (isCyclic || batches.length === 0) return;

      // Reset nodes to pending except batch 0 which becomes in_progress
      const updatedNodes = nodes.map(n => {
        if (batches[0].includes(n.id)) {
          const updatedAssigned = (n.context.assignedAgents || []).map(a => ({
            ...a,
            status: 'thinking' as const,
            currentThought: a.currentThought || `Analyzing contracts and execution plan for ${n.label}...`,
          }));
          return {
            ...n,
            status: 'in_progress' as NodeStatus,
            context: {
              ...n.context,
              assignedAgents: updatedAssigned,
            },
          };
        }
        return {
          ...n,
          status: 'pending' as NodeStatus,
          context: {
            ...n.context,
            assignedAgents: (n.context.assignedAgents || []).map(a => ({ ...a, status: 'queued' as const })),
          },
        };
      });

      set({
        isSimulating: true,
        simulationStep: 0,
        simulationBatches: batches,
        nodes: updatedNodes,
      });

      // Log start events
      batches[0].forEach(nodeId => {
        const n = nodes.find(x => x.id === nodeId);
        if (!n) return;
        const agents = n.context.assignedAgents || [];
        if (agents.length === 0) {
          get().addActivityEvent({
            agentId: 'agent-auto',
            agentName: n.context.role || 'Agent',
            agentRole: n.context.role || 'Worker',
            agentColor: '#1a73e8',
            agentAvatar: '🤖',
            nodeId: n.id,
            nodeLabel: n.label,
            actionType: 'started_work',
            detail: `Started execution on "${n.label}".`,
          });
        } else if (agents.length === 1) {
          get().addActivityEvent({
            agentId: agents[0].id,
            agentName: agents[0].name,
            agentRole: agents[0].role,
            agentColor: agents[0].color,
            agentAvatar: agents[0].avatar,
            nodeId: n.id,
            nodeLabel: n.label,
            actionType: 'started_work',
            detail: `${agents[0].name} (${agents[0].role}) dispatched on "${n.label}".`,
          });
        } else {
          const mode = n.context.collaborationMode || 'parallel_subtasks';
          const modeLabel = mode === 'debate_consensus' ? 'Debate & Consensus' : mode === 'pair_programming' ? 'Pair Execution' : 'Parallel Collaboration';
          get().addActivityEvent({
            agentId: agents[0].id,
            agentName: agents.map(a => a.name).join(' & '),
            agentRole: modeLabel,
            agentColor: '#9334e6',
            agentAvatar: '👥',
            nodeId: n.id,
            nodeLabel: n.label,
            actionType: 'collaborated',
            detail: `${agents.map(a => `${a.avatar} ${a.name}`).join(' and ')} collaborating on "${n.label}" (${modeLabel}).`,
          });
        }
      });
    },

    stepSimulation: () => {
      const { simulationStep, simulationBatches, nodes, edges } = get();
      if (simulationStep >= simulationBatches.length) {
        set({ isSimulating: false });
        return;
      }

      const currentBatch = simulationBatches[simulationStep];
      
      // Check if any node in current batch requires approval
      const needsApprovalNode = nodes.find(n => currentBatch.includes(n.id) && n.context.requiresHumanApproval && n.context.approvalStatus !== 'approved');
      if (needsApprovalNode) {
        const haltedNodes = nodes.map(n => {
          if (n.id === needsApprovalNode.id) {
            return {
              ...n,
              context: {
                ...n.context,
                approvalStatus: 'pending' as const,
              },
            };
          }
          return n;
        });
        set({
          isSimulating: false,
          nodes: haltedNodes,
          selectedNodeId: needsApprovalNode.id,
          selectedNodeIds: [needsApprovalNode.id],
        });
        get().addActivityEvent({
          agentId: 'agent-council',
          agentName: 'Council Gate',
          agentRole: 'Supervisor Gate',
          agentColor: '#ea4335',
          agentAvatar: '🛡️',
          nodeId: needsApprovalNode.id,
          nodeLabel: needsApprovalNode.label,
          actionType: 'blocked',
          detail: `Execution paused at Human Review Gate: Awaiting supervisor sign-off on "${needsApprovalNode.label}".`,
        });
        return;
      }

      const nextStep = simulationStep + 1;
      const nextBatch = simulationBatches[nextStep] || [];

      // Generate payloads for completed nodes in currentBatch
      const newPayloadsMap: Record<string, Record<string, ArtifactPayload>> = {};
      currentBatch.forEach(nodeId => {
        const n = nodes.find(x => x.id === nodeId);
        if (!n) return;
        const outputs = n.context.outputArtifacts || [];
        const payloads: Record<string, ArtifactPayload> = { ...(n.context.artifactPayloads || {}) };
        if (outputs.length === 0) {
          const defName = `${n.label.toLowerCase().replace(/[^a-z0-9]/g, '_')}_output.json`;
          payloads[defName] = createSyntheticArtifactPayload(defName, n.context.role, n.label);
        } else {
          outputs.forEach(art => {
            if (!payloads[art]) payloads[art] = createSyntheticArtifactPayload(art, n.context.role, n.label);
          });
        }
        newPayloadsMap[nodeId] = payloads;

        // Log completion to activityStream
        const agents = n.context.assignedAgents || [];
        const agentName = agents.length > 0 ? agents.map(a => a.name).join(' & ') : (n.context.role || 'Agent');
        const avatar = agents.length > 0 ? agents[0].avatar : '🤖';
        const color = agents.length > 0 ? agents[0].color : '#1e8e3e';
        get().addActivityEvent({
          agentId: agents.length > 0 ? agents[0].id : 'agent-auto',
          agentName,
          agentRole: n.context.role || 'Worker',
          agentColor: color,
          agentAvatar: avatar,
          nodeId: n.id,
          nodeLabel: n.label,
          actionType: 'completed',
          detail: `Completed "${n.label}". Emitted artifacts: ${Object.keys(payloads).join(', ')}.`,
        });
      });

      // Pass payloads downstream
      const updatedEdges = edges.map(e => {
        if (currentBatch.includes(e.source)) {
          const p = newPayloadsMap[e.source];
          return {
            ...e,
            animated: true,
            dataPayloadPassed: p ? Object.keys(p) : e.dataPayloadPassed,
          };
        }
        return e;
      });

      const updatedNodes = nodes.map(n => {
        if (currentBatch.includes(n.id)) {
          const updatedAssigned = (n.context.assignedAgents || []).map(a => ({
            ...a,
            status: 'completed' as const,
            progress: 100,
          }));
          return {
            ...n,
            status: 'completed' as NodeStatus,
            context: {
              ...n.context,
              assignedAgents: updatedAssigned,
              artifactPayloads: {
                ...(n.context.artifactPayloads || {}),
                ...(newPayloadsMap[n.id] || {}),
              },
            },
          };
        }
        if (nextBatch.includes(n.id)) {
          // Gather payloads from upstream
          const incomingEdges = edges.filter(e => e.target === n.id);
          let combinedPayloads = { ...(n.context.artifactPayloads || {}) };
          incomingEdges.forEach(e => {
            if (newPayloadsMap[e.source]) {
              combinedPayloads = { ...combinedPayloads, ...newPayloadsMap[e.source] };
            }
          });

          const updatedAssigned = (n.context.assignedAgents || []).map(a => ({
            ...a,
            status: 'thinking' as const,
            progress: 30,
          }));

          return {
            ...n,
            status: 'in_progress' as NodeStatus,
            context: {
              ...n.context,
              assignedAgents: updatedAssigned,
              artifactPayloads: combinedPayloads,
            },
          };
        }
        return n;
      });

      // If next batch is starting, log parallel asynchronous events
      if (nextBatch.length > 1) {
        get().addActivityEvent({
          agentId: 'swarm-fanout',
          agentName: 'Parallel Mesh',
          agentRole: 'Async Fan-Out',
          agentColor: '#1a73e8',
          agentAvatar: '⚡',
          nodeId: nextBatch[0],
          nodeLabel: `${nextBatch.length} Parallel Nodes`,
          actionType: 'started_work',
          detail: `Parallel Asynchronous Fan-Out: ${nextBatch.length} nodes running concurrently on separate agent worker threads.`,
        });
      }

      nextBatch.forEach(nodeId => {
        const n = nodes.find(x => x.id === nodeId);
        if (!n) return;
        const agents = n.context.assignedAgents || [];
        if (agents.length > 1) {
          const mode = n.context.collaborationMode || 'parallel_subtasks';
          const modeLabel = mode === 'debate_consensus' ? 'Debate & Consensus' : mode === 'pair_programming' ? 'Pair Execution' : 'Parallel Collaboration';
          get().addActivityEvent({
            agentId: agents[0].id,
            agentName: agents.map(a => a.name).join(' & '),
            agentRole: modeLabel,
            agentColor: '#9334e6',
            agentAvatar: '👥',
            nodeId: n.id,
            nodeLabel: n.label,
            actionType: 'collaborated',
            detail: `${agents.map(a => `${a.avatar} ${a.name}`).join(' and ')} collaborating on "${n.label}" (${modeLabel}).`,
          });
        } else if (agents.length === 1) {
          get().addActivityEvent({
            agentId: agents[0].id,
            agentName: agents[0].name,
            agentRole: agents[0].role,
            agentColor: agents[0].color,
            agentAvatar: agents[0].avatar,
            nodeId: n.id,
            nodeLabel: n.label,
            actionType: 'started_work',
            detail: `${agents[0].name} started async work on "${n.label}".`,
          });
        }
      });

      if (nextStep >= simulationBatches.length) {
        get().addActivityEvent({
          agentId: 'swarm-success',
          agentName: 'Swarm Coordinator',
          agentRole: 'Autonomous Orchestrator',
          agentColor: '#1e8e3e',
          agentAvatar: '🏆',
          nodeId: 'swarm-ship',
          nodeLabel: 'Topology Complete',
          actionType: 'completed',
          detail: `All autonomous work units and consensus gates verified successfully!`,
        });
      }

      set({
        simulationStep: nextStep,
        nodes: updatedNodes,
        edges: updatedEdges,
        isSimulating: nextStep < simulationBatches.length,
      });
    },

    pauseSimulation: () => {
      set({ isSimulating: false });
    },

    resetSimulation: () => {
      const sample = SAMPLE_TOPOLOGIES[0];
      set({
        isSimulating: false,
        simulationStep: 0,
        simulationBatches: [],
        nodes: JSON.parse(JSON.stringify(sample.nodes)),
      });
    },

    // Multi-Agent Swarm Actions
    setCockpitOpen: (isOpen) => set({ isCockpitOpen: isOpen }),
    setActiveFilterAgentId: (agentId) => set({ activeFilterAgentId: agentId }),

    addActivityEvent: (event) => {
      const newEvent: AgentActivityEvent = {
        ...event,
        id: `act-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
        timestamp: Date.now(),
      };
      set(state => ({
        activityStream: [newEvent, ...state.activityStream].slice(0, 100),
      }));
    },

    clearActivityStream: () => set({ activityStream: [] }),

    loadMultiAgentDemo: () => {
      const demo = SAMPLE_TOPOLOGIES.find(s => s.id === 'multi-agent-async-squad') || SAMPLE_TOPOLOGIES[0];
      saveSnapshot();
      set({
        nodes: JSON.parse(JSON.stringify(demo.nodes)),
        edges: JSON.parse(JSON.stringify(demo.edges)),
        selectedNodeId: 'swarm-spec',
        selectedNodeIds: ['swarm-spec'],
        isCockpitOpen: true,
        activityStream: [
          {
            id: `act-${Date.now()}-1`,
            timestamp: Date.now(),
            agentId: 'agent-sage',
            agentName: 'Sage',
            agentRole: 'Architect',
            agentColor: '#9334e6',
            agentAvatar: '🧠',
            nodeId: 'swarm-spec',
            nodeLabel: 'API Architecture & Security Contract',
            actionType: 'claimed_node',
            detail: 'Demo Swarm initialized: 6 specialized agents dispatched across graph topology.',
          },
          {
            id: `act-${Date.now()}-2`,
            timestamp: Date.now() + 100,
            agentId: 'agent-sentinel',
            agentName: 'Sentinel',
            agentRole: 'SecurityAnalyst',
            agentColor: '#ea4335',
            agentAvatar: '🛡️',
            nodeId: 'swarm-spec',
            nodeLabel: 'API Architecture & Security Contract',
            actionType: 'collaborated',
            detail: 'Paired with Sage on shared node in Debate & Consensus mode.',
          },
        ],
      });
      setTimeout(() => {
        get().startSimulation();
      }, 400);
    },

    assignAgentToNode: (nodeId, agent) => {
      saveSnapshot();
      const nodes = get().nodes.map(n => {
        if (n.id === nodeId) {
          const currentAgents = n.context.assignedAgents || [];
          if (currentAgents.some(a => a.id === agent.id)) return n;
          return {
            ...n,
            context: {
              ...n.context,
              assignedAgents: [...currentAgents, agent],
              collaborationMode: (currentAgents.length + 1 > 1) ? (n.context.collaborationMode || 'parallel_subtasks') : 'solo',
            },
          };
        }
        return n;
      });
      set({ nodes });
      get().addActivityEvent({
        agentId: agent.id,
        agentName: agent.name,
        agentRole: agent.role,
        agentColor: agent.color,
        agentAvatar: agent.avatar,
        nodeId,
        nodeLabel: nodes.find(n => n.id === nodeId)?.label || nodeId,
        actionType: 'claimed_node',
        detail: `${agent.name} assigned to node "${nodes.find(n => n.id === nodeId)?.label || nodeId}".`,
      });
    },

    removeAgentFromNode: (nodeId, agentId) => {
      saveSnapshot();
      const nodes = get().nodes.map(n => {
        if (n.id === nodeId) {
          const remaining = (n.context.assignedAgents || []).filter(a => a.id !== agentId);
          return {
            ...n,
            context: {
              ...n.context,
              assignedAgents: remaining,
              collaborationMode: remaining.length <= 1 ? 'solo' : n.context.collaborationMode,
            },
          };
        }
        return n;
      });
      set({ nodes });
    },

    setNodeCollaborationMode: (nodeId, mode) => {
      saveSnapshot();
      const nodes = get().nodes.map(n => {
        if (n.id === nodeId) {
          return {
            ...n,
            context: {
              ...n.context,
              collaborationMode: mode,
            },
          };
        }
        return n;
      });
      set({ nodes });
    },

    setTheme: (theme) => {
      if (typeof document !== 'undefined') {
        const isLight = theme === 'default' || theme === 'light' || theme === 'latte';
        if (isLight) {
          document.documentElement.classList.remove('dark');
        } else {
          document.documentElement.classList.add('dark');
        }
        document.documentElement.setAttribute('data-theme', theme);
      }
      set({ theme });
    },

    toggleTheme: () => {
      const current = get().theme;
      const nextTheme = current === 'default' ? 'catpuccin' : (current === 'catpuccin' || current === 'mocha') ? 'light' : 'default';
      get().setTheme(nextTheme);
    },

    setViewMode: (viewMode) => set({ viewMode }),
    setSearchQuery: (searchQuery) => set({ searchQuery }),
    setFilterExecutionType: (filterExecutionType) => set({ filterExecutionType }),
    setFilterRole: (filterRole) => set({ filterRole }),
    setFilterStatus: (filterStatus) => set({ filterStatus }),
    setFilterType: (filterType) => set({ filterType }),

    undo: () => {
      const { history, future, nodes, edges } = get();
      if (history.length === 0) return;

      const previous = history[history.length - 1];
      const newHistory = history.slice(0, -1);
      const newFuture = [{ nodes, edges }, ...future];

      set({
        nodes: previous.nodes,
        edges: previous.edges,
        history: newHistory,
        future: newFuture,
      });
    },

    redo: () => {
      const { history, future, nodes, edges } = get();
      if (future.length === 0) return;

      const next = future[0];
      const newFuture = future.slice(1);
      const newHistory = [...history, { nodes, edges }];

      set({
        nodes: next.nodes,
        edges: next.edges,
        history: newHistory,
        future: newFuture,
      });
    },

    publishTopology: (metadata) => {
      const { nodes, edges, userTopologies } = get();
      const newTopology: CanonicalArchetype = {
        id: `user-topology-${Date.now()}`,
        name: metadata.name.trim() || 'Untitled Topology',
        category: (metadata.category as any) || 'coding',
        description: metadata.description.trim() || 'Custom user topology graph.',
        popularity: 80,
        complexity: 'Intermediate',
        status: 'ready',
        tags: metadata.tags.length > 0 ? metadata.tags : ['custom', 'user-published'],
        estimatedMinutes: 15,
        author: metadata.author.trim() || 'Anonymous User',
        whyItMatters: 'Custom user-created topology for specialized agent workflows.',
        nodes: JSON.parse(JSON.stringify(nodes)),
        edges: JSON.parse(JSON.stringify(edges)),
      };
      const updated = [newTopology, ...userTopologies];
      try {
        localStorage.setItem('topology_community_registry_v1', JSON.stringify(updated));
      } catch (e) {
        console.warn('LocalStorage save failed:', e);
      }
      set({ userTopologies: updated });
      return newTopology;
    },

    deleteUserTopology: (id) => {
      const { userTopologies } = get();
      const updated = userTopologies.filter(t => t.id !== id);
      try {
        localStorage.setItem('topology_community_registry_v1', JSON.stringify(updated));
      } catch (e) {
        console.warn('LocalStorage delete failed:', e);
      }
      set({ userTopologies: updated });
    },

    loadTopologyDirect: (nodes, edges) => {
      saveSnapshot();
      const isVertical = get().layoutDirection === 'TB';
      const finalNodes = isVertical
        ? (() => {
            const positions = calculateDagreLayout(nodes, edges, 'TB');
            return nodes.map(n => ({
              ...n,
              position: positions[n.id] || n.position,
            }));
          })()
        : JSON.parse(JSON.stringify(nodes));

      set({
        nodes: finalNodes,
        edges: JSON.parse(JSON.stringify(edges)),
        selectedNodeId: null,
        selectedNodeIds: [],
      });
    },

    loadSampleTopology: (sampleId) => {
      const { userTopologies, layoutDirection } = get();
      const canonical = CANONICAL_ARCHETYPES.find(a => a.id === sampleId);
      const userTop = userTopologies.find(u => u.id === sampleId);
      const sample = SAMPLE_TOPOLOGIES.find(s => s.id === sampleId);
      const found = (canonical && canonical.nodes.length > 0 ? canonical : null) || userTop || sample || SAMPLE_TOPOLOGIES[0];

      saveSnapshot();
      const isVertical = layoutDirection === 'TB';
      const finalNodes = isVertical
        ? (() => {
            const positions = calculateDagreLayout(found.nodes, found.edges, 'TB');
            return found.nodes.map(n => ({
              ...n,
              position: positions[n.id] || n.position,
            }));
          })()
        : JSON.parse(JSON.stringify(found.nodes));

      set({
        nodes: finalNodes,
        edges: JSON.parse(JSON.stringify(found.edges)),
        selectedNodeId: null,
        selectedNodeIds: [],
      });
    },

    importCanvasData: (jsonStr) => {
      try {
        const { nodes, edges } = importFromObsidianCanvas(jsonStr);
        if (nodes.length === 0) return false;
        saveSnapshot();
        set({ nodes, edges, selectedNodeId: null });
        return true;
      } catch (err) {
        console.error('Failed to import Obsidian canvas:', err);
        return false;
      }
    },

    setGraph: (nodes, edges) => {
      saveSnapshot();
      set({ nodes, edges });
    },

    resetGraph: () => {
      saveSnapshot();
      set({ nodes: [], edges: [], selectedNodeId: null });
    },

    getStats: () => {
      const { nodes } = get();
      return {
        total: nodes.length,
        completed: nodes.filter(n => n.status === 'completed').length,
        inProgress: nodes.filter(n => n.status === 'in_progress').length,
        blocked: nodes.filter(n => n.status === 'blocked').length,
        ready: nodes.filter(n => n.status === 'ready').length,
        pending: nodes.filter(n => n.status === 'pending').length,
      };
    },

    setLiveSyncConnected: (connected) => {
      set(s => ({
        liveSyncStatus: { ...s.liveSyncStatus, connected }
      }));
    },

    setLiveSyncHeartbeat: (timestamp) => {
      set(s => ({
        liveSyncStatus: { ...s.liveSyncStatus, lastHeartbeat: timestamp }
      }));
    },

    setDesktopNotificationsEnabled: (enabled) => {
      set(s => ({
        liveSyncStatus: { ...s.liveSyncStatus, desktopNotificationsEnabled: enabled }
      }));
    },

    setAudioChimesEnabled: (enabled) => {
      set(s => ({
        liveSyncStatus: { ...s.liveSyncStatus, audioChimesEnabled: enabled }
      }));
    },
  };
});
