import { TopologyNode, TopologyEdge } from '../types/topology';

/**
 * Generates an LLM prompt payload optimized for Gemini CLI, Claude, or autonomous agent executors.
 * Injects upstream artifacts, tool constraints, stopping conditions, and validation criteria.
 */
export function generateAgentPromptPayload(
  node: TopologyNode,
  allNodes: TopologyNode[] = [],
  edges: TopologyEdge[] = []
): string {
  // Determine upstream dependencies
  const incomingEdges = edges.filter(e => e.target === node.id);
  const upstreamNodes = allNodes.filter(n => incomingEdges.some(e => e.source === n.id));

  // Determine downstream dependencies
  const outgoingEdges = edges.filter(e => e.source === node.id);
  const downstreamNodes = allNodes.filter(n => outgoingEdges.some(e => e.target === n.id));

  const role = node.context?.role || 'Principal Software Architect';
  const engine = node.context?.modelEngine || 'gemini-2.5-pro';
  const execType = node.context?.executionType || 'autonomous_agent';
  const tools = node.context?.toolsRequired || [];
  const inputArtifacts = node.context?.inputArtifacts || [];
  const outputArtifacts = node.context?.outputArtifacts || [];
  const validation = node.context?.validationCriteria || 'Zero regressions, all edge cases handled';
  const stoppingCondition = node.context?.stoppingCondition;

  // Collect available artifact data from upstream nodes
  const availableArtifacts: Record<string, unknown> = {};
  upstreamNodes.forEach(up => {
    if (up.context?.artifactPayloads) {
      Object.entries(up.context.artifactPayloads).forEach(([name, payload]) => {
        availableArtifacts[name] = payload.content;
      });
    }
  });

  return `# AGENT TASK ASSIGNMENT: ${node.label.toUpperCase()}

You are dispatched as an autonomous agent unit within a Directed Acyclic Graph (DAG) workflow.

## 1. AGENT IDENTITY & EXECUTION SPECS
- **Assigned Role**: ${role}
- **Execution Mode**: ${execType}
- **Target Engine**: ${engine}
- **Priority**: ${node.priority.toUpperCase()}
- **Node ID**: \`${node.id}\`

## 2. OBJECTIVE & SCOPE
${node.description || 'Execute assigned task according to architectural requirements.'}

${node.context?.promptTemplate ? `### Additional Task Instructions:\n${node.context.promptTemplate}\n` : ''}
## 3. DEPENDENCY CONTEXT (UPSTREAM INPUTS)
${upstreamNodes.length > 0 
  ? upstreamNodes.map(up => `- **From Prerequisite Node [${up.label}]** (\`${up.id}\`): Status=${up.status}`).join('\n')
  : '- *No upstream dependencies (Root Initiation Node)*'
}

### Declared Input Artifacts:
${inputArtifacts.length > 0
  ? inputArtifacts.map(art => `- \`${art}\``).join('\n')
  : '- None required'
}

${Object.keys(availableArtifacts).length > 0 ? `### Upstream Artifact Payloads Provided:\n\`\`\`json\n${JSON.stringify(availableArtifacts, null, 2)}\n\`\`\`\n` : ''}
## 4. TOOL PERMISSIONS & ENVIRONMENT
${tools.length > 0 
  ? `Authorized Tools:\n${tools.map(t => `- \`${t}\``).join('\n')}` 
  : '- General read/write environment tools only'
}

## 5. CONTRACT OUTPUTS & VALIDATION
You must produce and emit the following output artifacts:
${outputArtifacts.length > 0
  ? outputArtifacts.map(out => `- \`${out}\``).join('\n')
  : `- \`${node.label.toLowerCase().replace(/[^a-z0-9]/g, '_')}_output.json\``
}

### Acceptance & Validation Criteria:
> ${validation}

${stoppingCondition?.expression ? `### Stopping Condition / Recursion Invariant:\n- Expression: \`${stoppingCondition.expression}\`\n- Description: ${stoppingCondition.description || 'Bounded execution invariant'}\n` : ''}
${downstreamNodes.length > 0 ? `### Downstream Consumers Awaiting Output:\n${downstreamNodes.map(d => `- [${d.label}] (expects input for next phase)`).join('\n')}\n` : ''}
## 6. CLI QUICK-RUN COMMAND
To run this unit via Gemini CLI:
\`\`\`bash
gemini run --role "${role}" --prompt "Execute task [${node.label}]. Follow validation criteria: ${validation}"
\`\`\`
`;
}

/**
 * Generates a zero-dependency, executable Python CLI workflow runner (run_topology.py)
 * that parses and topologically executes the DAG headlessly.
 */
export function generateHeadlessCliRunner(
  nodes: TopologyNode[],
  edges: TopologyEdge[]
): string {
  const dagManifest = JSON.stringify({ nodes, edges }, null, 2);

  return `#!/usr/bin/env python3
"""
Topology DAG Headless CLI Workflow Runner
Generated by Topology Agent v1.0
Zero-dependency Python 3 execution runtime with topological sorting and artifact passing.
"""

import json
import sys
import time
from collections import defaultdict, deque
from typing import Dict, List, Any, Set

# Inlined Topology Graph State Manifest
TOPOLOGY_MANIFEST = ${dagManifest}

def kahn_topological_sort(nodes: List[Dict[str, Any]], edges: List[Dict[str, Any]]) -> List[List[str]]:
    """
    Computes parallel execution batches via Kahn's algorithm (antichains of the DAG).
    """
    node_ids = {n["id"] for n in nodes}
    in_degree = {nid: 0 for nid in node_ids}
    adj = defaultdict(list)

    for edge in edges:
        src = edge["source"]
        tgt = edge["target"]
        if src in node_ids and tgt in node_ids:
            adj[src].append(tgt)
            in_degree[tgt] += 1

    queue = deque([nid for nid, deg in in_degree.items() if deg == 0])
    batches = []
    visited_count = 0

    while queue:
        batch_size = len(queue)
        current_batch = []
        for _ in range(batch_size):
            u = queue.popleft()
            current_batch.append(u)
            visited_count += 1
            for v in adj[u]:
                in_degree[v] -= 1
                if in_degree[v] == 0:
                    queue.append(v)
        batches.append(current_batch)

    if visited_count < len(node_ids):
        raise ValueError("Cyclic dependency detected! Graph is not a valid DAG.")

    return batches

def execute_node(node: Dict[str, Any], shared_artifacts: Dict[str, Any]) -> Dict[str, Any]:
    """
    Executes an individual agent/script node within the topology.
    """
    node_id = node["id"]
    label = node.get("label", node_id)
    node_type = node.get("type", "task")
    context = node.get("context", {})
    role = context.get("role", "General Agent")
    engine = context.get("modelEngine", "gemini-2.5-pro")
    exec_type = context.get("executionType", "autonomous_agent")
    tools = context.get("toolsRequired", [])
    inputs = context.get("inputArtifacts", [])
    outputs = context.get("outputArtifacts", [])
    validation = context.get("validationCriteria", "Accepted")

    print(f"\\n  [\\033[94mSTART\\033[0m] Node: {label} ({node_id})")
    print(f"         Role: {role} | Engine: {engine} | Mode: {exec_type}")
    if tools:
        print(f"         Tools: {', '.join(tools)}")

    # Check input artifacts
    missing_inputs = [inp for inp in inputs if inp not in shared_artifacts]
    if missing_inputs:
        print(f"         \\033[93mNotice\\033[0m: Inputs not yet in storage: {missing_inputs} (proceeding with defaults)")

    # Simulate execution duration
    time.sleep(0.35)

    # Produce declared outputs
    produced = {}
    if not outputs:
        default_name = f"{label.lower().replace(' ', '_')}_output.json"
        produced[default_name] = {
            "node_id": node_id,
            "status": "success",
            "timestamp": time.time(),
            "validation_note": validation
        }
    else:
        for out in outputs:
            produced[out] = {
                "artifact": out,
                "node_id": node_id,
                "status": "success",
                "timestamp": time.time(),
                "criteria_met": validation
            }

    print(f"  [\\033[92mDONE\\033[0m]  Produced: {list(produced.keys())}")
    return produced

def main():
    print("=" * 65)
    print(" TOPOLOGY HEADLESS WORKFLOW RUNNER")
    print(" Executing Autonomous Agent Plan Manifest")
    print("=" * 65)

    nodes = TOPOLOGY_MANIFEST.get("nodes", [])
    edges = TOPOLOGY_MANIFEST.get("edges", [])
    node_map = {n["id"]: n for n in nodes}

    print(f"Nodes declared: {len(nodes)} | Edges: {len(edges)}")

    try:
        batches = kahn_topological_sort(nodes, edges)
    except ValueError as e:
        print(f"\\033[91mError\\033[0m: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Execution plan resolved into {len(batches)} sequential parallel batch(es):")
    for i, batch in enumerate(batches):
        batch_labels = [node_map[nid].get("label", nid) for nid in batch]
        print(f"  Stage {i + 1}: {batch_labels}")

    shared_artifacts: Dict[str, Any] = {}
    total_start = time.time()

    for stage_idx, batch in enumerate(batches):
        print(f"\\n>>> EXECUTING STAGE {stage_idx + 1}/{len(batches)} ({len(batch)} parallel unit(s))")
        for node_id in batch:
            node = node_map[node_id]
            outputs = execute_node(node, shared_artifacts)
            shared_artifacts.update(outputs)

    duration = time.time() - total_start
    print("\\n" + "=" * 65)
    print(f"\\033[92mSUCCESS\\033[0m: Entire Topology completed in {duration:.2f}s!")
    print(f"Total emitted artifacts: {len(shared_artifacts)}")
    for name in shared_artifacts:
        print(f"  - {name}")
    print("=" * 65)

if __name__ == "__main__":
    main()
`;
}
